package com.example.tattle.ui.theme

import androidx.compose.runtime.compositionLocalOf

object LocalStrings {
    private val translations = mapOf(
        "English" to mapOf(
            "for_you" to "For You",
            "explore" to "Explore",
            "trending" to "Trending",
            "saved" to "Saved",
            "settings" to "Settings",
            "language" to "Language",
            "clear_history" to "Clear History",
            "next" to "Next",
            "finish" to "Finish",
            "back" to "Back",
            "app_name" to "Tattle",
            "your_neighborhood" to "Your Neighborhood, Your Voice",
            "continue_google" to "Continue with Google",
            "continue_phone" to "Continue with Phone Number",
            "continue_email" to "Continue with Email",
            "send_code" to "Send Code",
            "verify_continue" to "Verify & Continue",
            "verify_number" to "Verify your number",
            "enter_code_sent" to "Enter the code sent to",
            "edit_number" to "Edit Number",
            "magic_code" to "Send Magic Code",
            "verify_login" to "Verify & Login",
            "change_email" to "Change Email",
            "authenticating" to "Authenticating...",
            "email_login" to "Email Login",
            "google_login" to "Google Login",
            "sign_in_google" to "Sign in with Google",
            "invalid_credentials" to "Invalid credentials",
            "invalid_age" to "Please enter a valid age (13-100)",
            "select_language" to "Select Language",
            "close" to "CLOSE",
            "your_age" to "When were you born?",
            "age_desc" to "So we can keep your feed age-appropriate.",
            "dob_label" to "DOB",
            "age_label" to "AGE",
            "type_age_hint" to "or simply type your age",
            "invalid_date" to "Please enter a valid date",
            "terms_service" to "By continuing, you agree to our Terms of Service",
            "phone_hint" to "10-digit Number",
            "google_sim_msg" to "Simulating Google OAuth flow...",
            "trouble_signing_in" to "Trouble signing in?",
            "you_are_all_set" to "You're all set! We'll keep you posted.",
            "what_are_you_into" to "What are you into?",
            "pick_interests" to "Pick atleast 3 to tune your feed",
            "stay_in_loop" to "Stay in the loop",
            "notification_desc" to "Get notified about daily digests and breaking news so you never miss a beat.\nTap on the bell to enable.",
            "configure_experience" to "Configure your experience",
            "notifications" to "NOTIFICATIONS",
            "daily_briefings" to "Daily Briefings",
            "daily_briefings_desc" to "Morning summaries of critical news.",
            "breaking_alerts" to "Breaking Alerts",
            "breaking_alerts_desc" to "Real-time push for important events.",
            "your_interests" to "YOUR INTERESTS",
            "add" to "+ Add",
            "preferences" to "PREFERENCES",
            "clear_history_desc" to "Reset your reading progress",
            "select_your_language" to "Select your language",
            "choose_primary_language" to "Choose the primary language for your daily news digest",
            "entertainment" to "Entertainment",
            "bollywood" to "Bollywood",
            "gaming" to "Gaming",
            "tech" to "Tech",
            "climate" to "Climate",
            "pop_culture" to "Pop Culture",
            "money" to "Money",
            "science_space" to "Science & Space",
            "fashion" to "Fashion",
            "ai_robotics" to "AI & Robotics",
            "wellness" to "Wellness",
            "sports" to "Sports",
            "culture" to "Culture",
            "politics" to "Politics",
            "ad_free" to "AD FREE",
            "offline_msg" to "You're offline — showing saved cached stories.",
            "deck_empty" to "Deck Empty",
            "no_bookmarks" to "You haven't bookmarked any articles yet.",
            "new_stories_later" to "Come back later — new stories drop throughout the day.",
            "browse_feed" to "BROWSE FEED",
            "limit_reached" to "LIMIT REACHED",
            "daily_recap" to "Daily Recap",
            "cards_read" to "Cards Read",
            "streak" to "Streak",
            "streak_days" to "Days",
            "share_recap" to "SHARE YOUR RECAP",
            "tune_feed" to "TUNE YOUR FEED",
            "tech_ai" to "Tech & AI",
            "other_genres" to "Other Genres",
            "core_takeaways" to "CORE TAKEAWAYS",
            "why_it_matters" to "WHY IT MATTERS",
            "launch_full_report" to "LAUNCH FULL-DEPTH REPORT",
            "exclusive" to "TATTLE EXCLUSIVE",
            "following" to "Following",
            "follow_thread" to "Follow Thread",
            "up_next" to "UP NEXT",
            "help_improve" to "Help us improve",
            "survey_desc" to "Take a quick survey to help us tune your feed.",
            "skip" to "Skip",
            "claim_ad_free" to "CLAIM AD-FREE HOURS",
            "ad_desc" to "Watch a 15s ad to support us and get 3 hours of Tattle without interruptions.",
            "watch_ad" to "WATCH AD",
            "get_ad_free" to "GET AD-FREE",
            "search_hint" to "Search stories...",
            "categories_label" to "Categories",
            "read_history_label" to "READ HISTORY",
            "saved_articles_label" to "SAVED ARTICLES"
        ),
        "Hindi" to mapOf(
            "for_you" to "आपके लिए",
            "explore" to "एक्सप्लोर",
            "trending" to "ट्रेंडिंग",
            "saved" to "सेव किया गया",
            "settings" to "सेटिंग्स",
            "language" to "भाषा",
            "clear_history" to "हिस्ट्री साफ़ करें",
            "next" to "अगला",
            "finish" to "खत्म",
            "back" to "पीछे",
            "app_name" to "Tattle",
            "your_neighborhood" to "आपका पड़ोस, आपकी आवाज़",
            "continue_google" to "Google के साथ जारी रखें",
            "continue_phone" to "फोन नंबर के साथ जारी रखें",
            "continue_email" to "ईमेल के साथ जारी रखें",
            "send_code" to "कोड भेजें",
            "verify_continue" to "वेरिफाई और जारी रखें",
            "verify_number" to "अपना नंबर वेरिफाई करें",
            "enter_code_sent" to "कोड दर्ज करें जो यहाँ भेजा गया है:",
            "edit_number" to "नंबर बदलें",
            "magic_code" to "मैजिक कोड भेजें",
            "verify_login" to "वेरिफाई और लॉगिन",
            "change_email" to "ईमेल बदलें",
            "authenticating" to "प्रमाणित किया जा रहा है...",
            "email_login" to "ईमेल लॉगिन",
            "google_login" to "Google लॉगिन",
            "sign_in_google" to "Google के साथ साइन इन करें",
            "invalid_credentials" to "अमान्य क्रेडेंशियल",
            "invalid_age" to "कृपया एक वैध आयु दर्ज करें (13-100)",
            "select_language" to "भाषा चुनें",
            "close" to "बंद करें",
            "your_age" to "आपका जन्म कब हुआ था?",
            "age_desc" to "ताकि हम आपकी फीड को आपकी आयु के अनुरूप रख सकें।",
            "dob_label" to "जन्म तिथि",
            "age_label" to "आयु",
            "type_age_hint" to "या बस अपनी आयु टाइप करें",
            "invalid_date" to "कृपया एक वैध तिथि दर्ज करें",
            "terms_service" to "जारी रखकर, आप हमारी सेवा की शर्तों से सहमत होते हैं",
            "phone_hint" to "10 अंकों का नंबर",
            "google_sim_msg" to "Google OAuth फ्लो का अनुकरण किया जा रहा है...",
            "trouble_signing_in" to "साइन इन करने में परेशानी?",
            "you_are_all_set" to "सब तैयार है! हम आपको अपडेट रखेंगे।",
            "what_are_you_into" to "आपकी रुचि किसमें है?",
            "pick_interests" to "अपनी फीड को बेहतर बनाने के लिए कम से कम 3 चुनें",
            "stay_in_loop" to "जुड़े रहें",
            "notification_desc" to "डेली डाइजेस्ट और ब्रेकिंग न्यूज़ के बारे में सूचित रहें ताकि आप कभी पीछे न रहें।\nसक्षम करने के लिए घंटी पर टैप करें।",
            "configure_experience" to "अपने अनुभव को कॉन्फ़िगर करें",
            "notifications" to "सूचनाएं",
            "daily_briefings" to "डेली ब्रीफिंग",
            "daily_briefings_desc" to "महत्वपूर्ण समाचारों का सुबह का सारांश।",
            "breaking_alerts" to "ब्रेकिंग अलर्ट",
            "breaking_alerts_desc" to "महत्वपूर्ण घटनाओं के लिए रीयल-टाइम पुश।",
            "your_interests" to "आपकी रुचियां",
            "add" to "+ जोड़ें",
            "preferences" to "प्राथमिकताएं",
            "clear_history_desc" to "अपनी पढ़ने की प्रगति को रीसेट करें",
            "select_your_language" to "अपनी भाषा चुनें",
            "choose_primary_language" to "अपने दैनिक समाचार सारांश के लिए प्राथमिक भाषा चुनें",
            "entertainment" to "मनोरंजन",
            "bollywood" to "बॉलीवुड",
            "gaming" to "गेमिंग",
            "tech" to "टेक",
            "climate" to "जलवायु",
            "pop_culture" to "पॉप कल्चर",
            "money" to "पैसा",
            "science_space" to "विज्ञान और अंतरिक्ष",
            "fashion" to "फैशन",
            "ai_robotics" to "AI और रोबोटिक्स",
            "wellness" to "वेलनेस",
            "sports" to "खेल",
            "culture" to "संस्कृति",
            "politics" to "राजनीति",
            "ad_free" to "विज्ञापन मुक्त",
            "offline_msg" to "आप ऑफ़लाइन हैं — सेव की गई कहानियां दिखाई जा रही हैं।",
            "deck_empty" to "डेक खाली है",
            "no_bookmarks" to "आपने अभी तक कोई लेख बुकमार्क नहीं किया है।",
            "new_stories_later" to "बाद में वापस आएं — पूरे दिन नई कहानियां आती रहती हैं।",
            "browse_feed" to "फीड ब्राउज़ करें",
            "limit_reached" to "सीमा समाप्त",
            "daily_recap" to "दैनिक रीकैप",
            "cards_read" to "पढ़े गए कार्ड",
            "streak" to "स्ट्रीक",
            "streak_days" to "दिन",
            "share_recap" to "अपना रीकैप शेयर करें",
            "tune_feed" to "अपनी फीड ट्यून करें",
            "tech_ai" to "टेक और AI",
            "other_genres" to "अन्य श्रेणियां",
            "core_takeaways" to "मुख्य बातें",
            "why_it_matters" to "यह क्यों महत्वपूर्ण है",
            "launch_full_report" to "पूरी रिपोर्ट देखें",
            "exclusive" to "TATTLE एक्सक्लूसिव",
            "following" to "फॉलो कर रहे हैं",
            "follow_thread" to "थ्रेड फॉलो करें",
            "up_next" to "अगला",
            "help_improve" to "हमें बेहतर बनाने में मदद करें",
            "survey_desc" to "अपनी फीड को ट्यून करने में हमारी मदद करने के लिए एक छोटा सर्वे लें।",
            "skip" to "छोड़ें",
            "claim_ad_free" to "विज्ञापन-मुक्त घंटों का दावा करें",
            "ad_desc" to "हमारा समर्थन करने के लिए 15 सेकंड का विज्ञापन देखें और बिना किसी रुकावट के 3 घंटे Tattle पाएं।",
            "watch_ad" to "विज्ञापन देखें",
            "get_ad_free" to "विज्ञापन-मुक्त पाएं",
            "search_hint" to "कहानियां खोजें...",
            "categories_label" to "श्रेणियां",
            "read_history_label" to "रीड हिस्ट्री",
            "saved_articles_label" to "सेव किए गए लेख"
        )
    )

    fun get(key: String, language: String): String {
        return translations[language]?.get(key) ?: translations["English"]?.get(key) ?: key
    }
}

val LocalAppLanguage = compositionLocalOf { "English" }
