package com.example.tattle.ui.theme

import androidx.compose.runtime.compositionLocalOf

object LocalStrings {
    private val translations = mapOf(
        "English" to mapOf(
            "for_you" to "For You",
            "explore" to "Explore",
            "trending" to "Trending",
            "saved" to "Saved",
            "settings" to "Settings",
            "language" to "Language",
            "clear_history" to "Clear History",
            "next" to "Next",
            "finish" to "Finish",
            "back" to "Back",
            "app_name" to "Tattle",
            "your_neighborhood" to "Your Neighborhood, Your Voice",
            "continue_google" to "Continue with Google",
            "continue_phone" to "Continue with Phone Number",
            "continue_email" to "Continue with Email",
            "send_code" to "Send Code",
            "verify_continue" to "Verify & Continue",
            "verify_number" to "Verify your number",
            "enter_code_sent" to "Enter the code sent to",
            "edit_number" to "Edit Number",
            "magic_code" to "Send Magic Code",
            "verify_login" to "Verify & Login",
            "change_email" to "Change Email",
            "authenticating" to "Authenticating...",
            "email_login" to "Email Login",
            "google_login" to "Google Login",
            "sign_in_google" to "Sign in with Google",
            "invalid_credentials" to "Invalid credentials",
            "invalid_age" to "Please enter a valid age (13-100)",
            "select_language" to "Select Language",
            "close" to "CLOSE",
            "your_age" to "Your age?",
            "age_desc" to "So we can keep your feed age-appropriate.\n(Must be between 13 and 100)",
            "what_are_you_into" to "What are you into?",
            "pick_interests" to "Pick atleast 3 to tune your feed",
            "stay_in_loop" to "Stay in the loop",
            "notification_desc" to "Get notified about daily digests and breaking news so you never miss a beat.\nTap on the bell to enable.",
            "configure_experience" to "Configure your experience",
            "notifications" to "NOTIFICATIONS",
            "daily_briefings" to "Daily Briefings",
            "daily_briefings_desc" to "Morning summaries of critical news.",
            "breaking_alerts" to "Breaking Alerts",
            "breaking_alerts_desc" to "Real-time push for important events.",
            "your_interests" to "YOUR INTERESTS",
            "add" to "+ Add",
            "preferences" to "PREFERENCES",
            "clear_history_desc" to "Reset your reading progress",
            "select_your_language" to "Select your language",
            "choose_primary_language" to "Choose the primary language for your daily news digest",
            "entertainment" to "Entertainment",
            "bollywood" to "Bollywood",
            "gaming" to "Gaming",
            "tech" to "Tech",
            "climate" to "Climate",
            "pop_culture" to "Pop Culture",
            "money" to "Money",
            "science_space" to "Science & Space",
            "fashion" to "Fashion",
            "ai_robotics" to "AI & Robotics",
            "wellness" to "Wellness",
            "sports" to "Sports",
            "culture" to "Culture",
            "politics" to "Politics",
            "ad_free" to "AD FREE",
            "offline_msg" to "You're offline — showing saved cached stories.",
            "deck_empty" to "Deck Empty",
            "no_bookmarks" to "You haven't bookmarked any articles yet.",
            "new_stories_later" to "Come back later — new stories drop throughout the day.",
            "browse_feed" to "BROWSE FEED",
            "limit_reached" to "LIMIT REACHED",
            "daily_recap" to "Daily Recap",
            "cards_read" to "Cards Read",
            "streak" to "Streak",
            "streak_days" to "Days",
            "share_recap" to "SHARE YOUR RECAP",
            "tune_feed" to "TUNE YOUR FEED",
            "tech_ai" to "Tech & AI",
            "other_genres" to "Other Genres",
            "core_takeaways" to "CORE TAKEAWAYS",
            "why_it_matters" to "WHY IT MATTERS",
            "launch_full_report" to "LAUNCH FULL-DEPTH REPORT",
            "exclusive" to "TATTLE EXCLUSIVE",
            "following" to "Following",
            "follow_thread" to "Follow Thread",
            "up_next" to "UP NEXT",
            "help_improve" to "Help us improve",
            "survey_desc" to "Take a quick survey to help us tune your feed.",
            "skip" to "Skip",
            "claim_ad_free" to "CLAIM AD-FREE HOURS",
            "ad_desc" to "Watch a 15s ad to support us and get 3 hours of Tattle without interruptions.",
            "watch_ad" to "WATCH AD",
            "get_ad_free" to "GET AD-FREE"
        ),
        "Spanish" to mapOf(
            "for_you" to "Para ti",
            "explore" to "Explorar",
            "trending" to "Tendencias",
            "saved" to "Guardado",
            "settings" to "Ajustes",
            "language" to "Idioma",
            "clear_history" to "Borrar historial",
            "next" to "Siguiente",
            "finish" to "Finalizar",
            "back" to "Atrás",
            "app_name" to "Tattle",
            "your_neighborhood" to "Tu vecindario, tu voz",
            "continue_google" to "Continuar con Google",
            "continue_phone" to "Continuar con número de teléfono",
            "continue_email" to "Continuar con correo electrónico",
            "send_code" to "Enviar código",
            "verify_continue" to "Verificar y continuar",
            "verify_number" to "Verifica tu número",
            "enter_code_sent" to "Introduce el código enviado a",
            "edit_number" to "Editar número",
            "magic_code" to "Enviar código mágico",
            "verify_login" to "Verificar e iniciar sesión",
            "change_email" to "Cambiar correo",
            "authenticating" to "Autenticando...",
            "email_login" to "Inicio de sesión por correo",
            "google_login" to "Inicio de sesión con Google",
            "sign_in_google" to "Iniciar sesión con Google",
            "invalid_credentials" to "Credenciales no válidas",
            "invalid_age" to "Por favor, introduce una edad válida (13-100)",
            "select_language" to "Seleccionar idioma",
            "close" to "CERRAR",
            "your_age" to "¿Tu edad?",
            "age_desc" to "Para que podamos mantener tu feed adecuado para tu edad.\n(Debe estar entre 13 y 100)",
            "what_are_you_into" to "¿Qué te interesa?",
            "pick_interests" to "Elige al menos 3 para ajustar tu feed",
            "stay_in_loop" to "Mantente al tanto",
            "notification_desc" to "Recibe notificaciones sobre resúmenes diarios y noticias de última hora.\nToca la campana para activar.",
            "configure_experience" to "Configura tu experiencia",
            "notifications" to "NOTIFICACIONES",
            "daily_briefings" to "Resúmenes diarios",
            "daily_briefings_desc" to "Resúmenes matutinos de noticias críticas.",
            "breaking_alerts" to "Alertas de última hora",
            "breaking_alerts_desc" to "Notificaciones en tiempo real para eventos importantes.",
            "your_interests" to "TUS INTERESES",
            "add" to "+ Añadir",
            "preferences" to "PREFERENCIAS",
            "clear_history_desc" to "Reiniciar tu progreso de lectura",
            "select_your_language" to "Selecciona tu idioma",
            "choose_primary_language" to "Elige el idioma principal para tu resumen diario de noticias",
            "entertainment" to "Entretenimiento",
            "bollywood" to "Bollywood",
            "gaming" to "Juegos",
            "tech" to "Tecnología",
            "climate" to "Clima",
            "pop_culture" to "Cultura Pop",
            "money" to "Dinero",
            "science_space" to "Ciencia y Espacio",
            "fashion" to "Moda",
            "ai_robotics" to "IA y Robótica",
            "wellness" to "Bienestar",
            "sports" to "Deportes",
            "culture" to "Cultura",
            "politics" to "Política",
            "ad_free" to "SIN ANUNCIOS",
            "offline_msg" to "Estás desconectado: se muestran historias guardadas.",
            "deck_empty" to "Mazo vacío",
            "no_bookmarks" to "Aún no has guardado ningún artículo.",
            "new_stories_later" to "Vuelve más tarde: nuevas historias a lo largo del día.",
            "browse_feed" to "EXPLORAR FEED",
            "limit_reached" to "LÍMITE ALCANZADO",
            "daily_recap" to "Resumen diario",
            "cards_read" to "Tarjetas leídas",
            "streak" to "Racha",
            "streak_days" to "Días",
            "share_recap" to "COMPARTE TU RESUMEN",
            "tune_feed" to "AJUSTA TU FEED",
            "tech_ai" to "Tecnología e IA",
            "other_genres" to "Otros géneros",
            "core_takeaways" to "CONCLUSIONES PRINCIPALES",
            "why_it_matters" to "POR QUÉ IMPORTA",
            "launch_full_report" to "INICIAR INFORME COMPLETO",
            "exclusive" to "EXCLUSIVO DE TATTLE",
            "following" to "Siguiendo",
            "follow_thread" to "Seguir hilo",
            "up_next" to "A CONTINUACIÓN",
            "help_improve" to "Ayúdanos a mejorar",
            "survey_desc" to "Responde una encuesta rápida para ajustar tu feed.",
            "skip" to "Omitir",
            "claim_ad_free" to "RECLAMA HORAS SIN ANUNCIOS",
            "ad_desc" to "Mira un anuncio de 15s para apoyarnos y obtener 3 horas de Tattle sin interrupciones.",
            "watch_ad" to "VER ANUNCIO",
            "get_ad_free" to "OBTENER SIN ANUNCIOS"
        ),
        "French" to mapOf(
            "for_you" to "Pour vous",
            "explore" to "Explorer",
            "trending" to "Tendances",
            "saved" to "Enregistré",
            "settings" to "Paramètres",
            "language" to "Langue",
            "clear_history" to "Effacer l'historique",
            "next" to "Suivant",
            "finish" to "Terminer",
            "back" to "Retour",
            "app_name" to "Tattle",
            "your_neighborhood" to "Votre quartier, votre voix",
            "continue_google" to "Continuer avec Google",
            "continue_phone" to "Continuer avec le numéro de téléphone",
            "continue_email" to "Continuer avec l'e-mail",
            "send_code" to "Envoyer le code",
            "verify_continue" to "Vérifier et continuer",
            "verify_number" to "Vérifiez votre numéro",
            "enter_code_sent" to "Entrez le code envoyé à",
            "edit_number" to "Modifier le numéro",
            "magic_code" to "Envoyer le code magique",
            "verify_login" to "Vérifier et se connecter",
            "change_email" to "Changer l'e-mail",
            "authenticating" to "Authentification...",
            "email_login" to "Connexion par e-mail",
            "google_login" to "Connexion Google",
            "sign_in_google" to "Se connecter with Google",
            "invalid_credentials" to "Identifiants invalides",
            "invalid_age" to "Veuillez entrer un âge valide (13-100)",
            "select_language" to "Choisir la langue",
            "close" to "FERMER",
            "your_age" to "Votre âge ?",
            "age_desc" to "Pour que nous puissions adapter votre flux à votre âge.\n(Doit être compris entre 13 et 100)",
            "what_are_you_into" to "Qu'est-ce qui vous intéresse ?",
            "pick_interests" to "Choisissez au moins 3 pour ajuster votre flux",
            "stay_in_loop" to "Restez informé",
            "notification_desc" to "Soyez informé des résumés quotidiens et des actualités de dernière minute.\nAppuyez sur la cloche pour activer.",
            "configure_experience" to "Configurez votre expérience",
            "notifications" to "NOTIFICATIONS",
            "daily_briefings" to "Briefings quotidiens",
            "daily_briefings_desc" to "Résumés matinaux des nouvelles critiques.",
            "breaking_alerts" to "Alertes de dernière minute",
            "breaking_alerts_desc" to "Push en temps réel pour les événements importants.",
            "your_interests" to "VOS INTÉRÊTS",
            "add" to "+ Ajouter",
            "preferences" to "PRÉFÉRENCES",
            "clear_history_desc" to "Réinitialiser votre progression de lecture",
            "select_your_language" to "Choisissez votre langue",
            "choose_primary_language" to "Choisissez la langue principale pour votre résumé quotidien",
            "entertainment" to "Divertissement",
            "bollywood" to "Bollywood",
            "gaming" to "Jeux",
            "tech" to "Tech",
            "climate" to "Climat",
            "pop_culture" to "Culture Pop",
            "money" to "Argent",
            "science_space" to "Science et Espace",
            "fashion" to "Mode",
            "ai_robotics" to "IA et Robotique",
            "wellness" to "Bien-être",
            "sports" to "Sports",
            "culture" to "Culture",
            "politics" to "Politique",
            "ad_free" to "SANS PUB",
            "offline_msg" to "Vous êtes hors ligne — affichage des histoires enregistrées.",
            "deck_empty" to "Deck vide",
            "no_bookmarks" to "Vous n'avez pas encore enregistré d'articles.",
            "new_stories_later" to "Revenez plus tard — de nouvelles histoires arrivent.",
            "browse_feed" to "PARCOURIR LE FLUX",
            "limit_reached" to "LIMITE ATTEINTE",
            "daily_recap" to "Résumé quotidien",
            "cards_read" to "Cartes lues",
            "streak" to "Série",
            "streak_days" to "Jours",
            "share_recap" to "PARTAGEZ VOTRE RÉSUMÉ",
            "tune_feed" to "AJUSTEZ VOTRE FLUX",
            "tech_ai" to "Tech et IA",
            "other_genres" to "Autres genres",
            "core_takeaways" to "POINTS CLÉS",
            "why_it_matters" to "POURQUOI C'EST IMPORTANT",
            "launch_full_report" to "LANCER LE RAPPORT COMPLET",
            "exclusive" to "EXCLUSIVITÉ TATTLE",
            "following" to "Abonné",
            "follow_thread" to "Suivre le fil",
            "up_next" to "À SUIVRE",
            "help_improve" to "Aidez-nous à améliorer",
            "survey_desc" to "Répondez à un sondage rapide pour ajuster votre flux.",
            "skip" to "Passer",
            "claim_ad_free" to "RÉCLAMER DES HEURES SANS PUB",
            "ad_desc" to "Regardez une pub de 15s pour nous soutenir et obtenir 3 heures de Tattle sans interruptions.",
            "watch_ad" to "REGARDER LA PUB",
            "get_ad_free" to "OBTENIR SANS PUB"
        ),
        "German" to mapOf(
            "for_you" to "Für dich",
            "explore" to "Entdecken",
            "trending" to "Trends",
            "saved" to "Gespeichert",
            "settings" to "Einstellungen",
            "language" to "Sprache",
            "clear_history" to "Verlauf löschen",
            "next" to "Weiter",
            "finish" to "Fertig",
            "back" to "Zurück",
            "app_name" to "Tattle",
            "your_neighborhood" to "Deine Nachbarschaft, deine Stimme",
            "continue_google" to "Mit Google fortfahren",
            "continue_phone" to "Mit Telefonnummer fortfahren",
            "continue_email" to "Mit E-Mail fortfahren",
            "send_code" to "Code senden",
            "verify_continue" to "Verifizieren & Weiter",
            "verify_number" to "Nummer verifizieren",
            "enter_code_sent" to "Gib den Code ein, der gesendet wurde an",
            "edit_number" to "Nummer bearbeiten",
            "magic_code" to "Magischen Code senden",
            "verify_login" to "Verifizieren & Einloggen",
            "change_email" to "E-Mail ändern",
            "authenticating" to "Authentifizierung...",
            "email_login" to "E-Mail-Login",
            "google_login" to "Google-Login",
            "sign_in_google" to "Mit Google anmelden",
            "invalid_credentials" to "Ungültige Anmeldedaten",
            "invalid_age" to "Bitte gib ein gültiges Alter ein (13-100)",
            "select_language" to "Sprache wählen",
            "close" to "SCHLIESSEN",
            "your_age" to "Dein Alter?",
            "age_desc" to "Damit wir deinen Feed altersgerecht halten können.\n(Muss zwischen 13 und 100 sein)",
            "what_are_you_into" to "Was interessiert dich?",
            "pick_interests" to "Wähle mindestens 3 aus, um deinen Feed abzustimmen",
            "stay_in_loop" to "Auf dem Laufenden bleiben",
            "notification_desc" to "Lass dich über tägliche Zusammenfassungen und Eilmeldungen informieren.\nZum Aktivieren auf die Glocke tippen.",
            "configure_experience" to "Erfahrung konfigurieren",
            "notifications" to "BENACHRICHTIGUNGEN",
            "daily_briefings" to "Tägliche Briefings",
            "daily_briefings_desc" to "Morgendliche Zusammenfassungen kritischer Nachrichten.",
            "breaking_alerts" to "Eilmeldungen",
            "breaking_alerts_desc" to "Echtzeit-Push für wichtige Ereignisse.",
            "your_interests" to "DEINE INTERESSEN",
            "add" to "+ Hinzufügen",
            "preferences" to "EINSTELLUNGEN",
            "clear_history_desc" to "Lesefortschritt zurücksetzen",
            "select_your_language" to "Wähle deine Sprache",
            "choose_primary_language" to "Wähle die Hauptsprache für deine tägliche Zusammenfassung",
            "entertainment" to "Unterhaltung",
            "bollywood" to "Bollywood",
            "gaming" to "Gaming",
            "tech" to "Tech",
            "climate" to "Klima",
            "pop_culture" to "Popkultur",
            "money" to "Geld",
            "science_space" to "Wissenschaft & Raumfahrt",
            "fashion" to "Mode",
            "ai_robotics" to "KI & Robotik",
            "wellness" to "Wellness",
            "sports" to "Sport",
            "culture" to "Kultur",
            "politics" to "Politik",
            "ad_free" to "WERBEFREI",
            "offline_msg" to "Du bist offline — gespeicherte Geschichten werden angezeigt.",
            "deck_empty" to "Deck leer",
            "no_bookmarks" to "Du hast noch keine Artikel gespeichert.",
            "new_stories_later" to "Komm später wieder — neue Geschichten folgen.",
            "browse_feed" to "FEED DURCHSUCHEN",
            "limit_reached" to "LIMIT ERREICHT",
            "daily_recap" to "Täglicher Rückblick",
            "cards_read" to "Gelesene Karten",
            "streak" to "Serie",
            "streak_days" to "Tage",
            "share_recap" to "RÜCKBLICK TEILEN",
            "tune_feed" to "FEED ANPASSEN",
            "tech_ai" to "Tech & KI",
            "other_genres" to "Andere Genres",
            "core_takeaways" to "WICHTIGSTE ERKENNTNISSE",
            "why_it_matters" to "WARUM ES WICHTIG IST",
            "launch_full_report" to "VOLLSTÄNDIGEN BERICHT ÖFFNEN",
            "exclusive" to "TATTLE EXKLUSIV",
            "following" to "Gefolgt",
            "follow_thread" to "Thread folgen",
            "up_next" to "NÄCHSTES",
            "help_improve" to "Hilf uns besser zu werden",
            "survey_desc" to "Nimm an einer kurzen Umfrage teil, um deinen Feed anzupassen.",
            "skip" to "Überspringen",
            "claim_ad_free" to "WERBEFREIE ZEIT SICHERN",
            "ad_desc" to "Schau eine 15s Anzeige, um uns zu unterstützen und erhalte 3 Stunden Tattle ohne Unterbrechungen.",
            "watch_ad" to "ANZEIGE SCHAUEN",
            "get_ad_free" to "WERBEFREI SICHERN"
        )
    )

    fun get(key: String, language: String): String {
        return translations[language]?.get(key) ?: translations["English"]?.get(key) ?: key
    }
}

val LocalAppLanguage = compositionLocalOf { "English" }
